# Generated by Django 4.2.4 on 2024-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_skill_jobposting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_skills',
            field=models.TextField(blank=True),
        ),
    ]
